#!/bin/bash
#append-cpr is released under the General Public License.
#Copyright (C) 2010-2012 Shezaan Topiwala
#This file is part of "Rabia Backups".

#append-cpr is free software: you can redistribute it and or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.

#append-cpr is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with append-cpr.  If not, see <http://www.gnu.org/licenses/>.

# This script appends the above copyright license.
for file in `ls -1 .`; do
    sed -i "2i\
#$file is released under the General Public License.\n\
#Copyright (C) 2010-2012 Shezaan Topiwala\n\
#This file is part of \"Rabia Backups\".\n\
\n\
#$file is free software: you can redistribute it and or modify\n\
#it under the terms of the GNU General Public License as published by\n\
#the Free Software Foundation, either version 3 of the License, or\n\
#(at your option) any later version.\n\
\n\
#$file is distributed in the hope that it will be useful,\n\
#but WITHOUT ANY WARRANTY; without even the implied warranty of\n\
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n\
#GNU General Public License for more details.\n\
\n\
#You should have received a copy of the GNU General Public License\n\
#along with $file.  If not, see <http://www.gnu.org/licenses/>." $file   
done

