#!/bin/bash
#backup-headers-git is released under the General Public License.
#Copyright (C) 2010-2012 Shezaan Topiwala
#This file is part of "Rabia Backups".

#backup-headers is free software: you can redistribute it and or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.

#backup-headers is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with backup-headers.  If not, see <http://www.gnu.org/licenses/>.

BIN_GIT=$HOME/rabia-backups # Parent directory for all "backup scripts" and "backup-config".
BACKUP_DAILY_GIT=$BIN_GIT/backup-daily-git # Executable for daily backups.
BACKUP_CONFIG_GIT=$BIN_GIT/backup-config-git # Location of configuration file.
BACKUP_TARGET_GIT=/tmp # Parent destination where all backups will be stored. Must be changed to meet your criteria.
LOG_DIR_GIT=/tmp/backup-logs-git # Location of log files.
DISK_SPACE_ALERT=90 # Backups are aborted if this disk space threshold is reached.
BACKUP_USER="backup-git" # Default remote and local backup user. This user can be overridden in the config file.
VCS_USER="vcs" # GIT account that serves up the repos.
ADMIN_EMAILS="admin1@example.com, admin2@example.com"

### DO NOT EDIT BELOW THIS LINE ###
TODAY=`date +%F@%T`
BACKUP_CONFIG_DAILY_GIT=$LOG_DIR_GIT/backup-config-daily-git # Automatically created by the respective executable
BACKUP_LOG_DAILY_GIT=$LOG_DIR_GIT/backup-log-daily-git
